<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Security;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SecuritiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET IDENTITY_INSERT securities ON');

        $securities = [
            // ── VN30 Stocks ──────────────────────────────────────────────

            // 1. VCB - Vietcombank
            [
                'symbol'         => 'VCB',
                'name'           => 'Vietcombank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 95000,
                'market_cap'     => 530000.00,
                'eps'            => 7500,
                'pe_ratio'       => 12.7,
                'dividend_yield' => 2.5,
                'volume'         => 3500000,
                'day_high'       => 95800,
                'day_low'        => 94200,
                'year_high'      => 105000,
                'year_low'       => 82000,
                'is_active'      => true,
            ],

            // 2. VIC - Vingroup
            [
                'symbol'         => 'VIC',
                'name'           => 'Vingroup JSC',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Real Estate',
                'industry'       => 'Real Estate Development',
                'current_price'  => 42000,
                'market_cap'     => 160000.00,
                'eps'            => 1800,
                'pe_ratio'       => 23.3,
                'dividend_yield' => 0.5,
                'volume'         => 4200000,
                'day_high'       => 42500,
                'day_low'        => 41500,
                'year_high'      => 52000,
                'year_low'       => 35000,
                'is_active'      => true,
            ],

            // 3. VNM - Vinamilk
            [
                'symbol'         => 'VNM',
                'name'           => 'Vinamilk',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Consumer Staples',
                'industry'       => 'FMCG',
                'current_price'  => 72000,
                'market_cap'     => 150000.00,
                'eps'            => 5200,
                'pe_ratio'       => 13.8,
                'dividend_yield' => 4.2,
                'volume'         => 1800000,
                'day_high'       => 72600,
                'day_low'        => 71500,
                'year_high'      => 78000,
                'year_low'       => 65000,
                'is_active'      => true,
            ],

            // 4. VPB - VPBank
            [
                'symbol'         => 'VPB',
                'name'           => 'VPBank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 19000,
                'market_cap'     => 150000.00,
                'eps'            => 2500,
                'pe_ratio'       => 7.6,
                'dividend_yield' => 3.8,
                'volume'         => 8500000,
                'day_high'       => 19200,
                'day_low'        => 18800,
                'year_high'      => 22500,
                'year_low'       => 15500,
                'is_active'      => true,
            ],

            // 5. HPG - Hoa Phat Group
            [
                'symbol'         => 'HPG',
                'name'           => 'Hoa Phat Group',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Materials',
                'industry'       => 'Steel',
                'current_price'  => 28000,
                'market_cap'     => 180000.00,
                'eps'            => 3200,
                'pe_ratio'       => 8.8,
                'dividend_yield' => 2.0,
                'volume'         => 7800000,
                'day_high'       => 28300,
                'day_low'        => 27600,
                'year_high'      => 32000,
                'year_low'       => 22000,
                'is_active'      => true,
            ],

            // 6. MSN - Masan Group
            [
                'symbol'         => 'MSN',
                'name'           => 'Masan Group',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Consumer Staples',
                'industry'       => 'Conglomerate',
                'current_price'  => 76000,
                'market_cap'     => 108000.00,
                'eps'            => 2800,
                'pe_ratio'       => 27.1,
                'dividend_yield' => 1.2,
                'volume'         => 2100000,
                'day_high'       => 76800,
                'day_low'        => 75200,
                'year_high'      => 86000,
                'year_low'       => 65000,
                'is_active'      => true,
            ],

            // 7. MBB - MB Bank
            [
                'symbol'         => 'MBB',
                'name'           => 'MB Bank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 24000,
                'market_cap'     => 125000.00,
                'eps'            => 3200,
                'pe_ratio'       => 7.5,
                'dividend_yield' => 3.5,
                'volume'         => 6200000,
                'day_high'       => 24200,
                'day_low'        => 23700,
                'year_high'      => 27000,
                'year_low'       => 19500,
                'is_active'      => true,
            ],

            // 8. STB - Sacombank
            [
                'symbol'         => 'STB',
                'name'           => 'Sacombank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 32000,
                'market_cap'     => 60000.00,
                'eps'            => 3800,
                'pe_ratio'       => 8.4,
                'dividend_yield' => 2.8,
                'volume'         => 5500000,
                'day_high'       => 32400,
                'day_low'        => 31600,
                'year_high'      => 36000,
                'year_low'       => 26500,
                'is_active'      => true,
            ],

            // 9. ACB - ACB Bank
            [
                'symbol'         => 'ACB',
                'name'           => 'ACB Bank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 25000,
                'market_cap'     => 85000.00,
                'eps'            => 3200,
                'pe_ratio'       => 7.8,
                'dividend_yield' => 3.2,
                'volume'         => 4800000,
                'day_high'       => 25300,
                'day_low'        => 24700,
                'year_high'      => 28500,
                'year_low'       => 21000,
                'is_active'      => true,
            ],

            // 10. TCB - Techcombank
            [
                'symbol'         => 'TCB',
                'name'           => 'Techcombank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 46000,
                'market_cap'     => 162000.00,
                'eps'            => 5200,
                'pe_ratio'       => 8.8,
                'dividend_yield' => 2.0,
                'volume'         => 3800000,
                'day_high'       => 46500,
                'day_low'        => 45500,
                'year_high'      => 51000,
                'year_low'       => 38000,
                'is_active'      => true,
            ],

            // 11. FPT - FPT Group
            [
                'symbol'         => 'FPT',
                'name'           => 'FPT Group',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Technology',
                'industry'       => 'Information Technology',
                'current_price'  => 135000,
                'market_cap'     => 185000.00,
                'eps'            => 6800,
                'pe_ratio'       => 19.9,
                'dividend_yield' => 2.8,
                'volume'         => 2900000,
                'day_high'       => 136500,
                'day_low'        => 133500,
                'year_high'      => 145000,
                'year_low'       => 102000,
                'is_active'      => true,
            ],

            // 12. SSI - SSI Securities
            [
                'symbol'         => 'SSI',
                'name'           => 'SSI Securities Corporation',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Securities',
                'current_price'  => 42000,
                'market_cap'     => 63000.00,
                'eps'            => 3500,
                'pe_ratio'       => 12.0,
                'dividend_yield' => 2.5,
                'volume'         => 5200000,
                'day_high'       => 42500,
                'day_low'        => 41500,
                'year_high'      => 48000,
                'year_low'       => 34000,
                'is_active'      => true,
            ],

            // 13. GAS - Petrovietnam Gas
            [
                'symbol'         => 'GAS',
                'name'           => 'Petrovietnam Gas',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Energy',
                'industry'       => 'Oil & Gas',
                'current_price'  => 82000,
                'market_cap'     => 157000.00,
                'eps'            => 6200,
                'pe_ratio'       => 13.2,
                'dividend_yield' => 3.5,
                'volume'         => 1500000,
                'day_high'       => 82800,
                'day_low'        => 81200,
                'year_high'      => 90000,
                'year_low'       => 72000,
                'is_active'      => true,
            ],

            // 14. SAB - Sabeco
            [
                'symbol'         => 'SAB',
                'name'           => 'Sabeco',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Consumer Staples',
                'industry'       => 'Beverage',
                'current_price'  => 56000,
                'market_cap'     => 72000.00,
                'eps'            => 3800,
                'pe_ratio'       => 14.7,
                'dividend_yield' => 4.5,
                'volume'         => 800000,
                'day_high'       => 56500,
                'day_low'        => 55500,
                'year_high'      => 62000,
                'year_low'       => 48000,
                'is_active'      => true,
            ],

            // 15. MWG - Mobile World
            [
                'symbol'         => 'MWG',
                'name'           => 'Mobile World Group',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Consumer Discretionary',
                'industry'       => 'Retail',
                'current_price'  => 46000,
                'market_cap'     => 67000.00,
                'eps'            => 2800,
                'pe_ratio'       => 16.4,
                'dividend_yield' => 1.5,
                'volume'         => 3500000,
                'day_high'       => 46500,
                'day_low'        => 45500,
                'year_high'      => 55000,
                'year_low'       => 38000,
                'is_active'      => true,
            ],

            // 16. VJC - Vietjet Air
            [
                'symbol'         => 'VJC',
                'name'           => 'Vietjet Air',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Industrials',
                'industry'       => 'Aviation',
                'current_price'  => 105000,
                'market_cap'     => 57000.00,
                'eps'            => 5200,
                'pe_ratio'       => 20.2,
                'dividend_yield' => 1.8,
                'volume'         => 1200000,
                'day_high'       => 106000,
                'day_low'        => 104000,
                'year_high'      => 118000,
                'year_low'       => 88000,
                'is_active'      => true,
            ],

            // 17. BVH - Bao Viet Holdings
            [
                'symbol'         => 'BVH',
                'name'           => 'Bao Viet Holdings',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Insurance',
                'current_price'  => 46000,
                'market_cap'     => 34000.00,
                'eps'            => 3500,
                'pe_ratio'       => 13.1,
                'dividend_yield' => 3.0,
                'volume'         => 900000,
                'day_high'       => 46500,
                'day_low'        => 45500,
                'year_high'      => 52000,
                'year_low'       => 39000,
                'is_active'      => true,
            ],

            // 18. PLX - Petrolimex
            [
                'symbol'         => 'PLX',
                'name'           => 'Petrolimex',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Energy',
                'industry'       => 'Oil & Gas',
                'current_price'  => 38000,
                'market_cap'     => 48000.00,
                'eps'            => 3200,
                'pe_ratio'       => 11.9,
                'dividend_yield' => 3.8,
                'volume'         => 2500000,
                'day_high'       => 38400,
                'day_low'        => 37600,
                'year_high'      => 42000,
                'year_low'       => 32000,
                'is_active'      => true,
            ],

            // 19. PNJ - Phu Nhuan Jewelry
            [
                'symbol'         => 'PNJ',
                'name'           => 'Phu Nhuan Jewelry JSC',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Consumer Discretionary',
                'industry'       => 'Retail',
                'current_price'  => 92000,
                'market_cap'     => 31000.00,
                'eps'            => 5800,
                'pe_ratio'       => 15.9,
                'dividend_yield' => 3.0,
                'volume'         => 1100000,
                'day_high'       => 92800,
                'day_low'        => 91200,
                'year_high'      => 100000,
                'year_low'       => 78000,
                'is_active'      => true,
            ],

            // 20. VRE - Vincom Retail
            [
                'symbol'         => 'VRE',
                'name'           => 'Vincom Retail',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Real Estate',
                'industry'       => 'Real Estate Development',
                'current_price'  => 25000,
                'market_cap'     => 57000.00,
                'eps'            => 1800,
                'pe_ratio'       => 13.9,
                'dividend_yield' => 2.2,
                'volume'         => 3200000,
                'day_high'       => 25300,
                'day_low'        => 24700,
                'year_high'      => 29000,
                'year_low'       => 21000,
                'is_active'      => true,
            ],

            // 21. NVL - Novaland
            [
                'symbol'         => 'NVL',
                'name'           => 'Novaland Group',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Real Estate',
                'industry'       => 'Real Estate Development',
                'current_price'  => 16000,
                'market_cap'     => 31000.00,
                'eps'            => 1200,
                'pe_ratio'       => 13.3,
                'dividend_yield' => 1.0,
                'volume'         => 5800000,
                'day_high'       => 16200,
                'day_low'        => 15800,
                'year_high'      => 20500,
                'year_low'       => 12000,
                'is_active'      => true,
            ],

            // 22. KDH - KDH Real Estate
            [
                'symbol'         => 'KDH',
                'name'           => 'KDH Real Estate',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Real Estate',
                'industry'       => 'Real Estate Development',
                'current_price'  => 34000,
                'market_cap'     => 25000.00,
                'eps'            => 2200,
                'pe_ratio'       => 15.5,
                'dividend_yield' => 1.8,
                'volume'         => 1800000,
                'day_high'       => 34400,
                'day_low'        => 33600,
                'year_high'      => 39000,
                'year_low'       => 28000,
                'is_active'      => true,
            ],

            // 23. PDR - Phat Dat Real Estate
            [
                'symbol'         => 'PDR',
                'name'           => 'Phat Dat Real Estate',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Real Estate',
                'industry'       => 'Real Estate Development',
                'current_price'  => 58000,
                'market_cap'     => 22000.00,
                'eps'            => 2800,
                'pe_ratio'       => 20.7,
                'dividend_yield' => 1.2,
                'volume'         => 2500000,
                'day_high'       => 58600,
                'day_low'        => 57400,
                'year_high'      => 68000,
                'year_low'       => 45000,
                'is_active'      => true,
            ],

            // 24. CTG - VietinBank
            [
                'symbol'         => 'CTG',
                'name'           => 'VietinBank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 32000,
                'market_cap'     => 170000.00,
                'eps'            => 3500,
                'pe_ratio'       => 9.1,
                'dividend_yield' => 3.5,
                'volume'         => 4500000,
                'day_high'       => 32400,
                'day_low'        => 31600,
                'year_high'      => 36000,
                'year_low'       => 26000,
                'is_active'      => true,
            ],

            // 25. BID - BIDV
            [
                'symbol'         => 'BID',
                'name'           => 'BIDV',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 50000,
                'market_cap'     => 280000.00,
                'eps'            => 4500,
                'pe_ratio'       => 11.1,
                'dividend_yield' => 3.0,
                'volume'         => 3200000,
                'day_high'       => 50500,
                'day_low'        => 49500,
                'year_high'      => 55000,
                'year_low'       => 42000,
                'is_active'      => true,
            ],

            // 26. TPB - TPBank
            [
                'symbol'         => 'TPB',
                'name'           => 'TPBank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 16000,
                'market_cap'     => 42000.00,
                'eps'            => 2200,
                'pe_ratio'       => 7.3,
                'dividend_yield' => 4.0,
                'volume'         => 3800000,
                'day_high'       => 16200,
                'day_low'        => 15800,
                'year_high'      => 19000,
                'year_low'       => 13000,
                'is_active'      => true,
            ],

            // 27. SHB - SHB Bank
            [
                'symbol'         => 'SHB',
                'name'           => 'SHB Bank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 11000,
                'market_cap'     => 35000.00,
                'eps'            => 1500,
                'pe_ratio'       => 7.3,
                'dividend_yield' => 4.5,
                'volume'         => 6200000,
                'day_high'       => 11200,
                'day_low'        => 10800,
                'year_high'      => 13000,
                'year_low'       => 9000,
                'is_active'      => true,
            ],

            // 28. VND - VNDirect Securities
            [
                'symbol'         => 'VND',
                'name'           => 'VNDirect Securities',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Securities',
                'current_price'  => 22000,
                'market_cap'     => 32000.00,
                'eps'            => 2800,
                'pe_ratio'       => 7.9,
                'dividend_yield' => 2.8,
                'volume'         => 4800000,
                'day_high'       => 22300,
                'day_low'        => 21700,
                'year_high'      => 26000,
                'year_low'       => 17500,
                'is_active'      => true,
            ],

            // 29. HCM - HCM Securities
            [
                'symbol'         => 'HCM',
                'name'           => 'HCM Securities',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Securities',
                'current_price'  => 28000,
                'market_cap'     => 18000.00,
                'eps'            => 3200,
                'pe_ratio'       => 8.8,
                'dividend_yield' => 2.5,
                'volume'         => 2200000,
                'day_high'       => 28300,
                'day_low'        => 27700,
                'year_high'      => 32000,
                'year_low'       => 23000,
                'is_active'      => true,
            ],

            // 30. EIB - Eximbank
            [
                'symbol'         => 'EIB',
                'name'           => 'Eximbank',
                'exchange'       => 'HOSE',
                'type'           => 'stock',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 18000,
                'market_cap'     => 32000.00,
                'eps'            => 1800,
                'pe_ratio'       => 10.0,
                'dividend_yield' => 2.0,
                'volume'         => 3500000,
                'day_high'       => 18200,
                'day_low'        => 17800,
                'year_high'      => 21000,
                'year_low'       => 15000,
                'is_active'      => true,
            ],

            // ── ETFs ─────────────────────────────────────────────────────

            // 31. FUESSV30 - SSIAM VN30 ETF
            [
                'symbol'         => 'FUESSV30',
                'name'           => 'SSIAM VN30 ETF',
                'exchange'       => 'HOSE',
                'type'           => 'etf',
                'sector'         => 'Financials',
                'industry'       => 'Exchange Traded Fund',
                'current_price'  => 18000,
                'market_cap'     => 3500.00,
                'eps'            => null,
                'pe_ratio'       => null,
                'dividend_yield' => 1.8,
                'volume'         => 500000,
                'day_high'       => 18200,
                'day_low'        => 17800,
                'year_high'      => 21000,
                'year_low'       => 15500,
                'is_active'      => true,
            ],

            // 32. FUESSV50 - SSIAM VN50 ETF
            [
                'symbol'         => 'FUESSV50',
                'name'           => 'SSIAM VN50 ETF',
                'exchange'       => 'HOSE',
                'type'           => 'etf',
                'sector'         => 'Financials',
                'industry'       => 'Exchange Traded Fund',
                'current_price'  => 14000,
                'market_cap'     => 1200.00,
                'eps'            => null,
                'pe_ratio'       => null,
                'dividend_yield' => 1.5,
                'volume'         => 200000,
                'day_high'       => 14200,
                'day_low'        => 13800,
                'year_high'      => 16500,
                'year_low'       => 12000,
                'is_active'      => true,
            ],

            // ── Bonds ────────────────────────────────────────────────────

            // 33. TPV12301 - TPBank Bond 2023
            [
                'symbol'         => 'TPV12301',
                'name'           => 'TPBank Bond 2023',
                'exchange'       => 'HNX',
                'type'           => 'bond',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 100000,
                'market_cap'     => 5000.00,
                'eps'            => null,
                'pe_ratio'       => null,
                'dividend_yield' => 6.5,
                'volume'         => 50000,
                'day_high'       => 100500,
                'day_low'        => 99500,
                'year_high'      => 101000,
                'year_low'       => 98000,
                'is_active'      => true,
            ],

            // 34. VCB12102 - Vietcombank Bond 2021
            [
                'symbol'         => 'VCB12102',
                'name'           => 'Vietcombank Bond 2021',
                'exchange'       => 'HNX',
                'type'           => 'bond',
                'sector'         => 'Financials',
                'industry'       => 'Banking',
                'current_price'  => 100000,
                'market_cap'     => 8000.00,
                'eps'            => null,
                'pe_ratio'       => null,
                'dividend_yield' => 5.8,
                'volume'         => 30000,
                'day_high'       => 100500,
                'day_low'        => 99500,
                'year_high'      => 101500,
                'year_low'       => 98500,
                'is_active'      => true,
            ],
        ];

        foreach ($securities as $security) {
            Security::create($security);
        }

        DB::statement('SET IDENTITY_INSERT securities OFF');
    }
}
